Repository hmcts/hmc-cft-hearing-service, pull requests merged in 2021-11, with the labels that each got.

#13 CCD-2131: Address CVE-2021-42340
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-cft-hearing-service-pr-13

#6 HMAN 21: Database creation for Hearing Management Component
  build.gradle
  charts/hmc-cft-hearing-service/Chart.yaml
  charts/hmc-cft-hearing-service/values.preview.template.yaml
  charts/hmc-cft-hearing-service/values.yaml
  docker/database/Dockerfile
  docker/database/init-db.sh
  infrastructure/main.tf
  infrastructure/output.tf
  infrastructure/variables.tf
  src/functionalTest/resources/features/F-000/S-000.td.json
  src/main/java/uk/gov/hmcts/reform/hmc/Application.java
  src/main/resources/application.yaml
  src/main/resources/db/migration/V20211001_21__HMAN-21-HearingService.sql
Labels: ns:hmc, prd:hmc, rel:hmc-cft-hearing-service-pr-6

#14 CCD-2137: Address CVE-2021-22096
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-cft-hearing-service-pr-14

#11 HMAN-29 -Build generic Inbound Topic Subscriber
  build.gradle
  charts/hmc-cft-hearing-service/Chart.yaml
  charts/hmc-cft-hearing-service/values.preview.template.yaml
  charts/hmc-cft-hearing-service/values.yaml
  config/owasp/suppressions.xml
  src/integrationTest/java/uk/gov/hmcts/reform/hmc/BaseTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/hmc/WiremockFixtures.java
  src/integrationTest/java/uk/gov/hmcts/reform/hmc/config/MessageReaderFromTopicConfigurationIT.java
  src/integrationTest/java/uk/gov/hmcts/reform/hmc/controllers/GetWelcomeTest.java
  src/integrationTest/resources/application-itest.yaml
  src/main/java/uk/gov/hmcts/reform/hmc/ApplicationParams.java
  src/main/java/uk/gov/hmcts/reform/hmc/config/MessageReaderFromTopicConfiguration.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/hmc/ApplicationParamsTest.java
Labels: ns:hmc, prd:hmc, rel:hmc-cft-hearing-service-pr-11

#22 Update application.yaml
  src/main/resources/application.yaml
Labels: ns:hmc, prd:hmc, rel:hmc-cft-hearing-service-pr-22

#18 Update Jenkinsfile_CNP sync branches
  Jenkinsfile_CNP
Labels: ns:hmc, prd:hmc, rel:hmc-cft-hearing-service-pr-18

#25 CCD-2177: Review CVE suppressions
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-cft-hearing-service-pr-25

#26 CCD-2178: Address CVE-2021-37136 and CVE-2021-37137
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-cft-hearing-service-pr-26

#8 HMAN-22 Validate POST request
  build.gradle
  config/owasp/suppressions.xml
  src/integrationTest/java/uk/gov/hmcts/reform/hmc/WiremockFixtures.java
  src/integrationTest/java/uk/gov/hmcts/reform/hmc/controllers/GetWelcomeTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/hmc/controllers/HearingManagementControllerIT.java
  src/integrationTest/java/uk/gov/hmcts/reform/hmc/service/HearingManagementServiceIT.java
  src/main/java/uk/gov/hmcts/reform/hmc/controllers/HearingManagementController.java
  src/main/java/uk/gov/hmcts/reform/hmc/exceptions/ApiError.java
  src/main/java/uk/gov/hmcts/reform/hmc/exceptions/BadRequestException.java
  src/main/java/uk/gov/hmcts/reform/hmc/exceptions/RestExceptionHandler.java
  src/main/java/uk/gov/hmcts/reform/hmc/exceptions/ValidationError.java
  src/main/java/uk/gov/hmcts/reform/hmc/model/CaseCategory.java
  src/main/java/uk/gov/hmcts/reform/hmc/model/CaseDetails.java
  src/main/java/uk/gov/hmcts/reform/hmc/model/CategoryType.java
  src/main/java/uk/gov/hmcts/reform/hmc/model/Dow.java
  src/main/java/uk/gov/hmcts/reform/hmc/model/DowUnavailabilityType.java
  src/main/java/uk/gov/hmcts/reform/hmc/model/HearingDetails.java
  src/main/java/uk/gov/hmcts/reform/hmc/model/HearingLocation.java
  src/main/java/uk/gov/hmcts/reform/hmc/model/HearingRequest.java
  src/main/java/uk/gov/hmcts/reform/hmc/model/HearingWindow.java
  src/main/java/uk/gov/hmcts/reform/hmc/model/IndividualDetails.java
  src/main/java/uk/gov/hmcts/reform/hmc/model/LocationId.java
  src/main/java/uk/gov/hmcts/reform/hmc/model/OrganisationDetails.java
  src/main/java/uk/gov/hmcts/reform/hmc/model/PanelPreference.java
  src/main/java/uk/gov/hmcts/reform/hmc/model/PanelRequirements.java
  src/main/java/uk/gov/hmcts/reform/hmc/model/PartyDetails.java
  src/main/java/uk/gov/hmcts/reform/hmc/model/PartyType.java
  src/main/java/uk/gov/hmcts/reform/hmc/model/RelatedParty.java
  src/main/java/uk/gov/hmcts/reform/hmc/model/RequestDetails.java
  src/main/java/uk/gov/hmcts/reform/hmc/model/RequirementType.java
  src/main/java/uk/gov/hmcts/reform/hmc/model/UnavailabilityDow.java
  src/main/java/uk/gov/hmcts/reform/hmc/model/UnavailabilityRanges.java
  src/main/java/uk/gov/hmcts/reform/hmc/service/HearingManagementService.java
  src/main/java/uk/gov/hmcts/reform/hmc/service/HearingManagementServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/hmc/validator/EnumPattern.java
  src/main/java/uk/gov/hmcts/reform/hmc/validator/EnumPatternValidator.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/hmc/controllers/HearingManagementControllerTest.java
  src/test/java/uk/gov/hmcts/reform/hmc/service/HearingManagementServiceTest.java
  src/test/java/uk/gov/hmcts/reform/hmc/utils/TestingUtil.java
  src/test/java/uk/gov/hmcts/reform/hmc/validator/BeanValidatorTest.java
  src/test/java/uk/gov/hmcts/reform/hmc/validator/EnumPatternValidatorTest.java
Labels: ns:hmc, prd:hmc, rel:hmc-cft-hearing-service-pr-8
