Repository hmcts/hmc-cft-hearing-service, pull requests merged in 2022-12, with the labels that each got.

#332 CCD-4043 Fasterxml Jackson Upgrade
  build.gradle
Labels: ns:hmc, prd:hmc, rel:hmc-cft-hearing-service-pr-332

#337 HMAN-492 CVE-2021-37533 Suppression
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-cft-hearing-service-pr-337

#339 HMAN-495 Upgrade base charts for Jenkins enhancements - bumped java v…
  charts/hmc-cft-hearing-service/Chart.yaml
Labels: ns:hmc, prd:hmc, rel:hmc-cft-hearing-service-pr-339

#334 CCD-4050: Fix Jenkins pipeline warnings
  Jenkinsfile_CNP
  Jenkinsfile_nightly
Labels: ns:hmc, prd:hmc, rel:hmc-cft-hearing-service-pr-334

#341 HMAN-497 CVE-2022-41881 Suppression
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-cft-hearing-service-pr-341

#343 Update suppressions.xml
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-cft-hearing-service-pr-343
