Repository hmcts/hmc-cft-hearing-service, pull requests merged in 2022-11, with the labels that each got.

#323 HMAN-454 CVE-2022-31690, CVE-2022-31690 HMAN-455 CVE-2022-42252 Suppr…
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-cft-hearing-service-pr-323

#318 HMAN-441: Monitor failures with the Hearing Service
  src/integrationTest/java/uk/gov/hmcts/reform/hmc/config/MessageProcessorIT.java
  src/integrationTest/java/uk/gov/hmcts/reform/hmc/config/MessageSenderToTopicConfigurationIT.java
  src/main/java/uk/gov/hmcts/reform/hmc/config/MessageProcessor.java
  src/main/java/uk/gov/hmcts/reform/hmc/config/MessageSenderToQueueConfiguration.java
  src/main/java/uk/gov/hmcts/reform/hmc/config/MessageSenderToTopicConfiguration.java
  src/main/java/uk/gov/hmcts/reform/hmc/constants/Constants.java
  src/main/java/uk/gov/hmcts/reform/hmc/service/HearingManagementServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/hmc/service/InboundQueueServiceImpl.java
  src/test/java/uk/gov/hmcts/reform/hmc/service/HearingManagementServiceTest.java
  src/test/java/uk/gov/hmcts/reform/hmc/service/InboundQueueServiceTest.java
Labels: ns:hmc, prd:hmc, rel:hmc-cft-hearing-service-pr-318

#263 HMAN-348
  config/owasp/suppressions.xml
  src/main/java/uk/gov/hmcts/reform/hmc/config/MessageSenderToQueueConfiguration.java
  src/main/java/uk/gov/hmcts/reform/hmc/config/MessageSenderToTopicConfiguration.java
  src/main/java/uk/gov/hmcts/reform/hmc/repository/DefaultFutureHearingRepository.java
  src/main/resources/application.yaml
Labels: ns:hmc, prd:hmc, rel:hmc-cft-hearing-service-pr-263

#328 HMAN-477 - Whitelist PRL
  src/main/resources/application.yaml
Labels: ns:hmc, prd:hmc, rel:hmc-cft-hearing-service-pr-328

#317 HMAN-432 Fix for CVE-2022-38752- update snakeyaml to version 1.32
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-cft-hearing-service-pr-317

#324 HMAN-438
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-cft-hearing-service-pr-324

#325 HMAN-455,HMAN-454: Tomcat and Spring Security
  build.gradle
  config/owasp/suppressions.xml
  src/integrationTest/java/uk/gov/hmcts/reform/hmc/BaseTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/hmc/wiremock/extensions/DynamicOAuthJwkSetResponseTransformer.java
  src/integrationTest/resources/wiremock-stubs/oauth-jwk-set.json
  src/main/java/uk/gov/hmcts/reform/hmc/config/SecurityConfiguration.java
  src/test/java/uk/gov/hmcts/reform/hmc/utils/KeyGenerator.java
Labels: ns:hmc, prd:hmc, rel:hmc-cft-hearing-service-pr-325

#299 HMAN-329 CVE-2022-34305 tomcat upgrade 9.0.65, suppression removed
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-cft-hearing-service-pr-299

#330 Fix hmc-cft-hearing-service CVEs
  build.gradle
  charts/hmc-cft-hearing-service/Chart.yaml
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-cft-hearing-service-pr-330
