Repository hmcts/hmc-cft-hearing-service, pull requests merged in 2022-09, with the labels that each got.

#296 HMAN-410 - Support `user-added-comments` for `listingAutoChangeReasonCode`
  src/main/java/uk/gov/hmcts/reform/hmc/client/hmi/ListingReasonCode.java
  src/main/java/uk/gov/hmcts/reform/hmc/model/HearingDetails.java
Labels: ns:hmc, prd:hmc, rel:hmc-cft-hearing-service-pr-296

#295 HMAN-405 HMAN-407 update logic for returning HearingDayPanel info
  src/contractTest/java/uk/gov/hmcts/reform/hmc/utility/HearingResponsePactUtil.java
  src/integrationTest/java/uk/gov/hmcts/reform/hmc/service/HearingManagementServiceIT.java
  src/main/java/uk/gov/hmcts/reform/hmc/helper/GetHearingResponseCommonCode.java
  src/main/java/uk/gov/hmcts/reform/hmc/helper/GetHearingResponseMapper.java
  src/main/java/uk/gov/hmcts/reform/hmc/helper/GetHearingsResponseMapper.java
  src/main/java/uk/gov/hmcts/reform/hmc/model/HearingDaySchedule.java
  src/test/java/uk/gov/hmcts/reform/hmc/helper/GetHearingResponseMapperTest.java
  src/test/java/uk/gov/hmcts/reform/hmc/helper/GetHearingsResponseMapperTest.java
Labels: ns:hmc, prd:hmc, rel:hmc-cft-hearing-service-pr-295

#298 Suppress CVE-2022-25857 in suppressions.xml
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-cft-hearing-service-pr-298

#300 HMAN-414
  src/integrationTest/java/uk/gov/hmcts/reform/hmc/controllers/HearingActualsManagementControllerIT.java
  src/main/java/uk/gov/hmcts/reform/hmc/helper/HearingActualsMapper.java
Labels: ns:hmc, prd:hmc, rel:hmc-cft-hearing-service-pr-300

#302 Create replica DB in ITHC
  infrastructure/main.tf
Labels: ns:hmc, prd:hmc, rel:hmc-cft-hearing-service-pr-302, add-or-update

#305 Create DB replicas in AAT and Prod
  infrastructure/aat.tfvars
  infrastructure/main.tf
  infrastructure/prod.tfvars
  infrastructure/variables.tf
Labels: ns:hmc, prd:hmc, add-or-update, rel:hmc-cft-hearing-service-pr-305

#308 Revert "Increase DB size in prod/perftest"
  infrastructure/perftest.tfvars
  infrastructure/prod.tfvars
Labels: ns:hmc, prd:hmc, destroy, rel:hmc-cft-hearing-service-pr-308

#310 HMAN-425 derived status AWAITING_ACCRUALS applies as soon as the star…
  src/main/java/uk/gov/hmcts/reform/hmc/data/HearingEntity.java
  src/test/java/uk/gov/hmcts/reform/hmc/data/HearingEntityTest.java
Labels: ns:hmc, prd:hmc, rel:hmc-cft-hearing-service-pr-310

#273 CCD-3539: Stop running Nightly builds on weekends
  Jenkinsfile_nightly
Labels: ns:hmc, prd:hmc, rel:hmc-cft-hearing-service-pr-273
