Repository hmcts/hmc-cft-hearing-service, pull requests merged in 2023-01, with the labels that each got.

#340 HMAN-494 Auto suppress CVE
  .github/workflows/dependency-check.yml
  .gitignore
  build.gradle
  gradle/suppress.gradle
Labels: ns:hmc, prd:hmc, rel:hmc-cft-hearing-service-pr-340

#345 .getProperty() changed to getenv() for pact properties
  Jenkinsfile_CNP
  build.gradle
Labels: ns:hmc, prd:hmc, rel:hmc-cft-hearing-service-pr-345

#347 HMAN-501: Update suppressions.xml
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-cft-hearing-service-pr-347

#349 HMAN-504: Exclude attributes containing 'null' value from /linkedH…
  Jenkinsfile_CNP
  src/integrationTest/resources/sql/insert-caseHearings_LinkedHearings.sql
  src/main/java/uk/gov/hmcts/reform/hmc/model/listassist/CaseListing.java
  src/main/java/uk/gov/hmcts/reform/hmc/model/listassist/HearingGroup.java
Labels: ns:hmc, prd:hmc, rel:hmc-cft-hearing-service-pr-349

#348 HMAN-502 Bump rse-gradle-java-plugin version
  build.gradle
Labels: ns:hmc, prd:hmc, rel:hmc-cft-hearing-service-pr-348

#351 HMAN-507 : updated Apache Tomcat to 9.0.69 and moved temporary suppressions to false positives
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-cft-hearing-service-pr-351

#352 Update Chart.yaml
  charts/hmc-cft-hearing-service/Chart.yaml
Labels: ns:hmc, prd:hmc, rel:hmc-cft-hearing-service-pr-352

#354 HMAN-503: Increase the characters to 2000 for VulnerabilityDetails…
  src/integrationTest/java/uk/gov/hmcts/reform/hmc/controllers/HearingManagementControllerIT.java
  src/main/java/uk/gov/hmcts/reform/hmc/exceptions/ValidationError.java
  src/main/java/uk/gov/hmcts/reform/hmc/model/IndividualDetails.java
  src/main/resources/db/migration/V20230125_503__HMAN-503-Update_vulnerability_details.sql
Labels: ns:hmc, prd:hmc, rel:hmc-cft-hearing-service-pr-354

#355 HMAN-511, HMAN-512, HMAN-513 update linked Hearing endpoints
  build.gradle
  src/integrationTest/java/uk/gov/hmcts/reform/hmc/service/LinkedHearingGroupServiceIT.java
  src/main/java/uk/gov/hmcts/reform/hmc/exceptions/FhBadRequestException.java
  src/main/java/uk/gov/hmcts/reform/hmc/exceptions/RestExceptionHandler.java
  src/main/java/uk/gov/hmcts/reform/hmc/service/LinkedHearingGroupServiceImpl.java
  src/test/java/uk/gov/hmcts/reform/hmc/service/LinkHearingGroupServiceTest.java
  src/test/java/uk/gov/hmcts/reform/hmc/service/LinkedHearingGroupServiceTest.java
Labels: ns:hmc, prd:hmc, rel:hmc-cft-hearing-service-pr-355, keep-helm
