Repository hmcts/hmc-cft-hearing-service, pull requests merged in 2023-03, with the labels that each got.

#367 CCD-4396 : Create .terraform-version
  infrastructure/.terraform-version
Labels: ns:hmc, prd:hmc, no-changes, rel:hmc-cft-hearing-service-pr-367

#259 HMAN-312 Use ServiceBus ProcessorClient instead of ReceiverClient to resolve queue failure issue
  config/owasp/suppressions.xml
  src/integrationTest/java/uk/gov/hmcts/reform/hmc/RestExceptionHandlerTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/hmc/config/MessageProcessorIT.java
  src/integrationTest/java/uk/gov/hmcts/reform/hmc/config/MessageSenderToQueueConfigurationIT.java
  src/integrationTest/java/uk/gov/hmcts/reform/hmc/config/MessageSenderToTopicConfigurationIT.java
  src/integrationTest/java/uk/gov/hmcts/reform/hmc/config/RestTemplateConfigurationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/hmc/config/SwaggerPublisherTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/hmc/controllers/GetWelcomeTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/hmc/controllers/HearingActualControllerIT.java
  src/integrationTest/java/uk/gov/hmcts/reform/hmc/controllers/PartiesNotifiedControllerIT.java
  src/integrationTest/java/uk/gov/hmcts/reform/hmc/data/DefaultRoleAssignmentRepositoryIT.java
  src/integrationTest/java/uk/gov/hmcts/reform/hmc/repository/CaseHearingRequestRepositoryIT.java
  src/integrationTest/java/uk/gov/hmcts/reform/hmc/service/HearingManagementServiceIT.java
  src/integrationTest/java/uk/gov/hmcts/reform/hmc/service/LinkedHearingGroupServiceIT.java
  src/main/java/uk/gov/hmcts/reform/hmc/config/MessageProcessor.java
  src/main/java/uk/gov/hmcts/reform/hmc/config/MessageReaderFromQueueConfiguration.java
  src/main/java/uk/gov/hmcts/reform/hmc/config/QueueClientConfig.java
  src/main/java/uk/gov/hmcts/reform/hmc/service/InboundQueueService.java
  src/main/java/uk/gov/hmcts/reform/hmc/service/InboundQueueServiceImpl.java
  src/test/java/uk/gov/hmcts/reform/hmc/client/futurehearing/HearingManagementInterfaceRequestInterceptorTest.java
  src/test/java/uk/gov/hmcts/reform/hmc/config/MessageProcessorTest.java
  src/test/java/uk/gov/hmcts/reform/hmc/service/HearingActualsServiceTest.java
  src/test/java/uk/gov/hmcts/reform/hmc/service/InboundQueueServiceTest.java
  src/test/java/uk/gov/hmcts/reform/hmc/utils/TestingUtil.java
Labels: ns:hmc, prd:hmc, rel:hmc-cft-hearing-service-pr-259

#370 HMAN-524 Upgrade dependencies to resolve CVE-2023-24998
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-cft-hearing-service-pr-370

#369 update befta-fw version to 8.7.11
  build.gradle
Labels: ns:hmc, prd:hmc, rel:hmc-cft-hearing-service-pr-369
