Repository hmcts/hmc-cft-hearing-service, pull requests merged in 2023-11, with the labels that each got.

#399 HMAN-576 Fix CVE-2023-34035 by upgrading spring security version from…
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, add-or-update, rel:hmc-cft-hearing-service-pr-399

#418 Subnet suffix update
  infrastructure/main.tf
Labels: ns:hmc, prd:hmc, add-or-update, rel:hmc-cft-hearing-service-pr-418

#415 HMAN-590 fix Civil Duplicate Party participants in Hearings problem
  src/main/java/uk/gov/hmcts/reform/hmc/helper/HearingActualsMapper.java
  src/test/java/uk/gov/hmcts/reform/hmc/helper/HearingActualsMapperTest.java
Labels: ns:hmc, prd:hmc, destroy, rel:hmc-cft-hearing-service-pr-415, enable_keep_helm

#414 CCD-4771 : Fix CVE-2023-3511
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-cft-hearing-service-pr-414
