Repository hmcts/hmc-cft-hearing-service, pull requests merged in 2023-09, with the labels that each got.

#386 HMAN-546 - Upgrade to Java 17 in all HMC Repos
  .github/workflows/dependency-check.yml
  .github/workflows/swagger.yml
  .gitignore
  Dockerfile
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  lib/AI-Agent.xml
  lib/applicationinsights.json
Labels: ns:hmc, prd:hmc, rel:hmc-cft-hearing-service-pr-386

#396 HMAN-577- Failure on any amendment of the updated hearing request
  src/main/java/uk/gov/hmcts/reform/hmc/data/HearingEntity.java
  src/main/java/uk/gov/hmcts/reform/hmc/validator/LinkedHearingValidator.java
  src/test/java/uk/gov/hmcts/reform/hmc/data/HearingEntityTest.java
Labels: ns:hmc, prd:hmc, rel:hmc-cft-hearing-service-pr-396

#403 CCD-4845: renovate config
  .dependabot/config.yml
  .github/renovate.json
Labels: ns:hmc, prd:hmc, rel:hmc-cft-hearing-service-pr-403

#401 Upgrade gradle
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-cft-hearing-service-pr-401

#395 HMAN-531,HMAN-549,HMAN-548- HMC Pre-prod test environment alignment
  src/contractTest/java/uk/gov/hmcts/reform/hmc/provider/HearingManagementGetHearingsProviderTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/hmc/BaseTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/hmc/RestExceptionHandlerTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/hmc/config/MessageSenderToQueueConfigurationIT.java
  src/integrationTest/java/uk/gov/hmcts/reform/hmc/config/MessageSenderToTopicConfigurationIT.java
  src/integrationTest/java/uk/gov/hmcts/reform/hmc/controllers/HearingManagementControllerIT.java
  src/integrationTest/java/uk/gov/hmcts/reform/hmc/service/HearingManagementServiceIT.java
  src/integrationTest/resources/application-itest.yaml
  src/main/java/uk/gov/hmcts/reform/hmc/ApplicationParams.java
  src/main/java/uk/gov/hmcts/reform/hmc/config/MessageSenderToQueueConfiguration.java
  src/main/java/uk/gov/hmcts/reform/hmc/config/MessageSenderToTopicConfiguration.java
  src/main/java/uk/gov/hmcts/reform/hmc/constants/Constants.java
  src/main/java/uk/gov/hmcts/reform/hmc/controllers/HearingManagementController.java
  src/main/java/uk/gov/hmcts/reform/hmc/data/HearingEntity.java
  src/main/java/uk/gov/hmcts/reform/hmc/exceptions/ValidationError.java
  src/main/java/uk/gov/hmcts/reform/hmc/helper/HearingMapper.java
  src/main/java/uk/gov/hmcts/reform/hmc/service/HearingManagementService.java
  src/main/java/uk/gov/hmcts/reform/hmc/service/HearingManagementServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/hmc/service/InboundQueueServiceImpl.java
  src/main/resources/application.yaml
  src/main/resources/db/migration/V20230804_531__HMAN-531-add_deployment_id_Hearing.sql
  src/test/java/uk/gov/hmcts/reform/hmc/controllers/HearingManagementControllerTest.java
  src/test/java/uk/gov/hmcts/reform/hmc/service/HearingManagementServiceTest.java
  src/test/java/uk/gov/hmcts/reform/hmc/service/InboundQueueServiceTest.java
Labels: ns:hmc, prd:hmc, rel:hmc-cft-hearing-service-pr-395
