Repository hmcts/hmc-cft-hearing-service, pull requests merged in 2024-06, with the labels that each got.

#499 HMAN-647 Update values.yaml with flexible server
  charts/hmc-cft-hearing-service/Chart.yaml
  charts/hmc-cft-hearing-service/values.yaml
Labels: ns:hmc, prd:hmc, rel:hmc-cft-hearing-service-pr-499

#500 ✿✿✿✿ DO NOT MERGE ✿✿✿✿ HMAN-647 Decomission v11 Postgres databases
  infrastructure/.terraform-version
  infrastructure/main.tf
  infrastructure/state.tf
Labels: ns:hmc, prd:hmc, aat/destroy, DO NOT MERGE, prod/destroy, rel:hmc-cft-hearing-service-pr-500

#498 HMAN-837 update room id field length
  src/main/resources/db/migration/V20240613_837__HMAN-837-update_room_id_field_length.sql
Labels: ns:hmc, prd:hmc, rel:hmc-cft-hearing-service-pr-498

#504 fix fortify gradle task
  build.gradle
Labels: ns:hmc, prd:hmc, rel:hmc-cft-hearing-service-pr-504

#495 HMAN-642 UnNotified Hearings
  UnNotifiedHearings/WithEndDateTime.sql
  UnNotifiedHearings/WithoutEndDateTime.sql
Labels: ns:hmc, prd:hmc, rel:hmc-cft-hearing-service-pr-495

#379 HMAN-543: Hearing id has same hearing request version in hearing table
  src/integrationTest/resources/sql/insert-caseHearings_LinkedHearings.sql
  src/main/resources/db/migration/V20230510_543__HMAN-543-Add_Constraint_CaseHearingRequest.sql
Labels: ns:hmc, prd:hmc, rel:hmc-cft-hearing-service-pr-379

#503 Chore adding back demo branchsync Update Jenkinsfile_CNP
  Jenkinsfile_CNP
Labels: ns:hmc, prd:hmc, rel:hmc-cft-hearing-service-pr-503
