Repository hmcts/hmc-cft-hearing-service, pull requests merged in 2025-04, with the labels that each got.

#563 HMAN-943 Update controller method name
  src/main/java/uk/gov/hmcts/reform/hmc/controllers/LinkHearingGroupController.java
Labels: ns:hmc, prd:hmc, rel:hmc-cft-hearing-service-pr-563

#565 HMAN-561 : Add 'partyType' field to /hearingsActuals (GET) - response
  src/main/java/uk/gov/hmcts/reform/hmc/helper/GetHearingActualsResponseMapper.java
  src/main/java/uk/gov/hmcts/reform/hmc/model/hearingactuals/Party.java
  src/test/java/uk/gov/hmcts/reform/hmc/helper/GetHearingActualsResponseMapperTest.java
Labels: ns:hmc, prd:hmc, rel:hmc-cft-hearing-service-pr-565

#569 Ccd 6280 suppress CVE 2024 38286
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-cft-hearing-service-pr-569

#570 Update state.tf bump azurerm
  infrastructure/state.tf
Labels: ns:hmc, prd:hmc, aat/add-or-update, prod/no-changes, rel:hmc-cft-hearing-service-pr-570

#571 DTSPO-25342 - import PlatOps group
  infrastructure/import.tf
Labels: ns:hmc, prd:hmc, aat/add-or-update, prod/add-or-update, rel:hmc-cft-hearing-service-pr-571

#550 CME-229: Update azurerm and AD
  infrastructure/main.tf
  infrastructure/state.tf
Labels: ns:hmc, prd:hmc, aat/add-or-update, prod/add-or-update, rel:hmc-cft-hearing-service-pr-550

#529 HMAN-581 Refactored Oct 2024
  .gitignore
  src/main/java/uk/gov/hmcts/reform/hmc/config/PendingStatusType.java
  src/main/java/uk/gov/hmcts/reform/hmc/data/PendingRequestEntity.java
  src/main/java/uk/gov/hmcts/reform/hmc/repository/PendingRequestRepository.java
  src/main/java/uk/gov/hmcts/reform/hmc/service/HearingManagementServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/hmc/service/PendingRequestService.java
  src/main/java/uk/gov/hmcts/reform/hmc/service/PendingRequestServiceImpl.java
  src/main/resources/db/migration/V20241016_581__HMAN-581-RecreatePendingRequests.sql
  src/main/resources/db/migration/V20250204_581__HMAN-581-Alter_PendingRequests_allownull.sql
  src/test/java/uk/gov/hmcts/reform/hmc/entity/PendingRequestEntityTest.java
  src/test/java/uk/gov/hmcts/reform/hmc/service/HearingManagementServiceTest.java
  src/test/java/uk/gov/hmcts/reform/hmc/service/PendingRequestServiceImplTest.java
Labels: ns:hmc, prd:hmc, enable_keep_helm, aat/destroy, prod/destroy, rel:hmc-cft-hearing-service-pr-529
