Repository hmcts/hmc-cft-hearing-service, pull requests merged in 2025-06, with the labels that each got.

#592 Update suppressions.xml
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-cft-hearing-service-pr-592

#580 CME-509: replace jitpack with azure
  build.gradle
  config/owasp/suppressions.xml
  settings.gradle
Labels: ns:hmc, prd:hmc, aat/destroy, prod/destroy, rel:hmc-cft-hearing-service-pr-580

#588 Fix CVE-2023-52428
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-cft-hearing-service-pr-588
