Repository hmcts/hmc-cft-hearing-service, pull requests merged in 2025-05, with the labels that each got.

#575 CCD-6353 :: Suppressions for CVE-2025-31650, CVE-2025-31651
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-cft-hearing-service-pr-575

#578 Suppression CVE-2024-24549, CVE-2024-23672
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-cft-hearing-service-pr-578

#574 CME-367: REenable ithc sync
  Jenkinsfile_CNP
Labels: ns:hmc, prd:hmc, rel:hmc-cft-hearing-service-pr-574
