Repository hmcts/hmc-cft-hearing-service, pull requests merged in 2025-09, with the labels that each got.

#610 CCD-6796 :: Add suppressions
  config/owasp/suppressions.xml
Labels: ns:hmc, prd:hmc, rel:hmc-cft-hearing-service-pr-610

#611 Added import block for pgsql_adadmin
  infrastructure/import.tf
  infrastructure/main.tf
Labels: ns:hmc, prd:hmc, aat/add-or-update, prod/no-changes, rel:hmc-cft-hearing-service-pr-611

#577 HMAN- 605 Allow Future Actuals for non-hearing days
  src/integrationTest/java/uk/gov/hmcts/reform/hmc/controllers/HearingActualsManagementControllerIT.java
  src/main/java/uk/gov/hmcts/reform/hmc/model/ActualHearingDay.java
  src/main/java/uk/gov/hmcts/reform/hmc/model/HearingActualsOutcome.java
  src/main/java/uk/gov/hmcts/reform/hmc/service/HearingActualsServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/hmc/validator/HearingActualsValidator.java
  src/test/java/uk/gov/hmcts/reform/hmc/model/HearingActualTest.java
  src/test/java/uk/gov/hmcts/reform/hmc/service/HearingActualsServiceTest.java
  src/test/java/uk/gov/hmcts/reform/hmc/utils/TestingUtil.java
  src/test/java/uk/gov/hmcts/reform/hmc/validator/HearingActualsValidatorTest.java
Labels: ns:hmc, prd:hmc, aat/no-changes, prod/destroy, rel:hmc-cft-hearing-service-pr-577
